config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: %i[new create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[create new]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.1/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
  <%= simple_form_for (@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category, collection: %w[chinese italian japanese french belgian], selected: 0 %>
    <%= f.input :phone_number %>
    <%= f.submit "Submit restaurant", class: "btn btn-primary" %>
  <% end %>

app/views/restaurants/edit.html.erb
<div class="container d-flex justify-content-center">
  <div class="w-50 p-3">
    <h1>Edit restaurant</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/restaurants/index.html.erb
<h1>List all restaurants</h1>
<% @restaurants.each do |restaurant|%>
  <h2><%= link_to restaurant.name, restaurant_path(restaurant)  %></h2>
<% end %>

<%= link_to "New Restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<div class="container d-flex justify-content-center">
  <div class="w-50 p-3">
    <h1>New Restaurant</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container d-flex justify-content-center">
  <!-- Content here -->
  <div class="w-75 p-3">
    <h1 class="text-center">Restaurant <%= @restaurant.name%></h1>
    <h2 class="text-center">Category: <%= @restaurant.category.capitalize %></h2>
    <h2 class="text-center">Phone number: <%= @restaurant.phone_number %></h2>
    <h2 class="text-center">Address: <%= @restaurant.address %></h2>

    <ul class="list-group ">
      <% if @restaurant.reviews.present? %>
        <% @restaurant.reviews.each do |review| %>
          <li class="list-group-item"><%= review.content%>
          <%= link_to review_path(review), method: :delete, data: { confirm: "Are you sure?" } do %>
          <i class="fa-solid fa-delete-left"></i>
          <% end %>
          </li>
        <% end %>
      <% else %>
        <li class="text-center list-group-item">Be the first to review <%= @restaurant.name %></li>
      <% end %>
    </ul>

  </div>
</div>
  <div class="container d-flex justify-content-around w-75 p-3">
    <%= link_to "Delete", restaurant_path(@restaurant), method: :delete,  data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    <%= link_to "Add a Review", new_restaurant_review_path(@restaurant), class: "btn btn-success" %>
    <%= link_to "All Restaurants", restaurants_path, class: "btn btn-primary" %>
    <%= link_to "Edit Restaurant", edit_restaurant_path, class: "btn btn-warning" %>
  </div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/edit.html.erb
<h1>New Review</h1>
<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<%= render 'form' %>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %> |
<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>